#!/usr/bin/env python3
"""Frontmatter audit for the trilingual ressources content tree.

This site's "content" is two things:

  1. Hand-authored legal pages (about / imprint / privacy / disclaimer),
     three languages each. Required keys: title.
  2. Programmatically-scaffolded view stubs under content/{de,en,fr}/
     nach_*/, generated by scripts/scaffold_hugo_content.py from
     i18n.py + sources_master.yml. Required keys: title, layout,
     params.filter (which slices the YAML database).

Plus the language-pickers (content/{de,en,fr}/_index.md) and the
overview page (content/{lang}/overview.md, layout: overview).

Author attribution is set site-wide in hugo.toml params.author and
emitted into every rendered <meta name="author"> by the Coder theme.
This script does NOT enforce a per-file `author:` key — that would
be ceremony without value. The post-build gate in CI (`audit_rendered_author`)
verifies the actual rendered HTML carries the meta tag.

Exit 1 on any missing required field.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---", re.DOTALL)


def parse_frontmatter(p: Path) -> dict | None:
    txt = p.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(txt)
    if not m:
        return None
    fm = yaml.safe_load(m.group(1)) or {}
    return fm if isinstance(fm, dict) else {}


def required(rel: Path) -> list[str]:
    parts = rel.parts
    name = rel.name
    posix = "/".join(parts)

    # any _index.md
    if name == "_index.md":
        return ["title"]

    # legal pages: content/{lang}/{about,imprint,privacy,disclaimer}.md
    legal = {"about.md", "imprint.md", "privacy.md", "disclaimer.md"}
    if name in legal and len(parts) == 3 and parts[0] == "content":
        return ["title"]

    # overview page: content/{lang}/overview.md
    if name == "overview.md" and len(parts) == 3 and parts[0] == "content":
        return ["title", "layout"]

    # view stubs under content/{lang}/nach_*/...
    if "nach_" in posix:
        return ["title", "layout", "params"]

    return ["title"]


def main() -> int:
    issues: list[tuple[Path, list[str]]] = []
    drafts: list[Path] = []
    seen = 0
    for md in sorted(CONTENT.rglob("*.md")):
        seen += 1
        rel = md.relative_to(ROOT)
        fm = parse_frontmatter(md)
        if fm is None:
            issues.append((rel, ["(no frontmatter)"]))
            continue
        missing = [k for k in required(rel) if k not in fm]
        # for stubs, also check the layout name matches and params.filter exists
        if "layout" in fm and fm["layout"] == "resource-listing":
            params = fm.get("params") or {}
            if not isinstance(params, dict) or "filter" not in params:
                missing.append("params.filter (required by layout: resource-listing)")
        if missing:
            issues.append((rel, missing))
        if fm.get("draft") is True:
            drafts.append(rel)

    print(f"audited {seen} content files under {CONTENT.relative_to(ROOT)}/")
    if drafts:
        print(f"\n{len(drafts)} draft files (not deployed):")
        for d in drafts:
            print(f"  - {d}")
    if issues:
        print(f"\n::error::missing required frontmatter in {len(issues)} file(s):")
        for path, miss in issues:
            print(f"  {path}: missing {', '.join(miss)}")
        return 1
    print("\nfrontmatter OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
