#!/usr/bin/env python3
"""One-shot Hugo content + i18n scaffold generator.

Reads the existing Quarto generators (`_scripts/i18n.py`,
`_scripts/build_pages.py`) which remain the source of truth for
UI strings and legal text, and emits:

  - i18n/{de,en,fr}.toml           Hugo native i18n
  - content/_index.md              Trilingual language picker
  - content/{lang}/_index.md       Per-language landing
  - content/{lang}/overview.md     Overview page (vis-network)
  - content/{lang}/{about,imprint,privacy,disclaimer}.md
                                   Verbatim port of the Python
                                   string literals
  - content/{lang}/nach_*/...md    ~120 view stubs with
                                   `layout: resource-listing` +
                                   `params.filter` frontmatter

This script is committed for transparency and re-runnability but
should be invoked **only** during the migration — once Hugo
content is in tree, edits go to those files directly.

Run from repo root:
    python scripts/scaffold_hugo_content.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from textwrap import indent

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "_scripts"))

import build_pages  # noqa: E402
from i18n import LANGS, UI, t  # noqa: E402

# -- helpers ----------------------------------------------------------

def write(rel: str, body: str) -> None:
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding="utf-8")


_PY_FMT = re.compile(r"\{(\w+)\}")


def to_go_template(s: str) -> str:
    """Convert Python `{name}` placeholders to Go template `{{ .name }}`.

    Hugo's i18n facility renders TOML "other = ..." values as Go
    templates. We only need to translate the placeholder syntax;
    everything else is untouched (including curly-free text).
    """
    return _PY_FMT.sub(lambda m: "{{ ." + m.group(1) + " }}", s)


def toml_escape(s: str) -> str:
    """Escape a string for a TOML basic string (double-quoted)."""
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
    )


# -- 1. i18n -----------------------------------------------------------

def emit_i18n() -> None:
    """One file per language: i18n/{lang}.toml.

    Each UI key becomes a [section] with `other = "..."`. Keys whose
    Python format string contains placeholders gain Go-template
    placeholders; templates render them via:

        {{ i18n "key" (dict "k" 7) }}
    """
    for lang in LANGS:
        lines = [
            "# Auto-generated by scripts/scaffold_hugo_content.py",
            "# Source of truth: _scripts/i18n.py (UI dict).",
            f"# Language: {lang}",
            "",
        ]
        for key in sorted(UI.keys()):
            entry = UI[key]
            value = entry.get(lang) or entry.get("de") or ""
            value = to_go_template(value)
            lines.append(f"[{key}]")
            lines.append(f'other = "{toml_escape(value)}"')
            lines.append("")
        write(f"i18n/{lang}.toml", "\n".join(lines))


# -- 2. legal pages ----------------------------------------------------

LEGAL_TITLE_KEY = {
    "about": "nav_about",
    "imprint": "nav_imprint",
    "privacy": "nav_privacy",
    "disclaimer": {
        "de": "Haftungsausschluss",
        "en": "Disclaimer",
        "fr": "Avis",
    },
}

LEGAL_DICTS = {
    "about": build_pages.ABOUT,
    "imprint": build_pages.IMPRINT,
    "privacy": build_pages.PRIVACY,
    "disclaimer": build_pages.DISCLAIMER,
}


def emit_legal() -> None:
    """Extract the byte-exact legal prose from build_pages.py.

    The Python literals already contain a YAML frontmatter block
    (`---\\ntitle: ...\\n---\\n`) followed by the markdown body.
    We strip that frontmatter and rebuild it for Hugo so URL
    aliases and ordering match what Hugo expects, but the body
    text is preserved verbatim.
    """
    for slug, dct in LEGAL_DICTS.items():
        for lang in LANGS:
            raw = dct[lang]
            # Strip leading frontmatter block.
            m = re.match(r"\A---\n(.*?)\n---\n(.*)", raw, flags=re.DOTALL)
            if not m:
                raise SystemExit(f"unexpected legal text shape: {slug}/{lang}")
            old_fm, body = m.group(1), m.group(2)
            # Recover any aliases from the old frontmatter.
            # In Hugo's multilingual mode with defaultContentLanguageInSubdir,
            # aliases are language-relative — strip the leading /<lang>/ if
            # the original Quarto alias hardcoded it.
            aliases = []
            lang_prefix = f"/{lang}/"
            for line in old_fm.splitlines():
                line = line.strip()
                if line.startswith("- /"):
                    a = line[2:].strip()
                    if a.startswith(lang_prefix):
                        a = "/" + a[len(lang_prefix):]
                    aliases.append(a)
            # Build new frontmatter.
            title = (
                LEGAL_TITLE_KEY[slug][lang]
                if isinstance(LEGAL_TITLE_KEY[slug], dict)
                else None
            )
            if title is None:
                title = t(LEGAL_TITLE_KEY[slug], lang)
            fm_lines = [
                "---",
                f'title: "{title}"',
            ]
            if aliases:
                fm_lines.append("aliases:")
                for a in aliases:
                    fm_lines.append(f"  - {a}")
            fm_lines.append("---")
            fm_lines.append("")
            new_fm = "\n".join(fm_lines)
            write(f"content/{lang}/{slug}.md", new_fm + body)


# -- 3. landings + overview + root picker ------------------------------

def emit_landings() -> None:
    """Per-language landing page using i18n keys.

    The body uses Hugo shortcodes (defined in layouts/_partials/
    shortcodes/) for the hero / card-grid. Falls back to raw HTML
    divs if shortcodes are not yet defined — Hugo renders divs
    untouched under markup.goldmark.renderer.unsafe = true.
    """
    for lang in LANGS:
        body = f"""---
title: "{t('landing_title', lang)}"
description: "{t('landing_subtitle', lang)}"
---

<div class="hero">
<div class="kicker">{t('kicker', lang)}</div>

{t('hero_lead', lang)}

</div>

## {t('entries_heading', lang)}

<div class="card-grid">

<div class="entry-card">

### [{t('nav_language', lang)}](nach_sprache/englisch/)

{t('entry_lang_lead', lang)}

</div>

<div class="entry-card">

### [{t('nav_skill', lang)}](nach_fertigkeit/hoeren/)

{t('entry_skill_lead', lang)}

</div>

<div class="entry-card">

### [{t('nav_level', lang)}](nach_niveau/a1/)

{t('entry_level_lead', lang)}

</div>

<div class="entry-card">

### [{t('nav_unit', lang)}](nach_unit/efl/)

{t('entry_unit_lead', lang)}

</div>

</div>

## {t('criteria_heading', lang)}

{t('criteria_text', lang)}
"""
        write(f"content/{lang}/_index.md", body)


def emit_overview() -> None:
    for lang in LANGS:
        body = f"""---
title: "{t('overview_title', lang)}"
description: "{t('overview_lead', lang)}"
layout: overview
---

{t('overview_lead', lang)}
"""
        write(f"content/{lang}/overview.md", body)


def emit_root_picker() -> None:
    """Root language picker.

    With per-language `contentDir` settings the root URL `/` does not
    map to any content file, so the picker lives at
    `static/index.html` (hand-authored, byte-stable). This function
    is a no-op kept for symmetry; static/index.html is committed.
    """
    return


# -- 4. view stubs -----------------------------------------------------

def stub(title: str, lead: str, filter_yaml: str) -> str:
    """A view-listing stub (YAML frontmatter).

    Hugo dispatches on `layout: resource-listing`. The template
    reads `.Params.filter` (a YAML map under `params:`) and
    slices site.Data.sources_master accordingly.
    """
    return (
        "---\n"
        f'title: "{title}"\n'
        f'description: "{lead}"\n'
        "layout: resource-listing\n"
        "params:\n"
        "  filter:\n"
        f"{filter_yaml}"
        "---\n"
    )


def emit_view_stubs() -> None:
    skills = ["hoeren", "lesen", "schreiben", "sprechen",
              "grammatik", "wortschatz", "landeskunde"]
    levels = ["a1", "a2", "b1", "b2", "c1"]

    languages_for_pages = {
        "englisch": "EN", "franzoesisch": "FR", "deutsch": "DE",
    }
    lang_full_keys = {
        "englisch": "lang_en_full",
        "franzoesisch": "lang_fr_full",
        "deutsch": "lang_de_full",
    }
    lang_lead_keys = {
        "englisch": "lead_lang_en",
        "franzoesisch": "lead_lang_fr",
        "deutsch": "lead_lang_de",
    }

    for lang in LANGS:
        # ----- by language ------
        for slug, code in languages_for_pages.items():
            title = t(lang_full_keys[slug], lang)
            lead = t(lang_lead_keys[slug], lang)
            fb = f'    language: "{code}"\n'
            write(f"content/{lang}/nach_sprache/{slug}.md",
                  stub(title, lead, fb))

        # ----- by skill ------
        for sk in skills:
            title = t(f"skill_{sk}", lang)
            lead = t(f"lead_skill_{sk}", lang)
            fb = f'    skill: "{sk}"\n'
            write(f"content/{lang}/nach_fertigkeit/{sk}.md",
                  stub(title, lead, fb))

        # ----- by level ------
        for lv in levels:
            title = lv.upper()
            lead = t(f"lead_lvl_{lv}", lang)
            fb = f'    cefr_level: "{lv.upper()}"\n'
            write(f"content/{lang}/nach_niveau/{lv}.md",
                  stub(title, lead, fb))

        # ----- by unit (EFL): kl05..kl13 plus index ------
        klasse = t("klasse", lang)
        index_title = t("unit_efl_overview", lang)
        index_lead = t("unit_efl_lead", lang)
        cards = "\n".join(
            f'<div class="entry-card">\n\n'
            f'### [{klasse} {k}](kl{k:02d}/)\n\n</div>\n'
            for k in range(5, 14)
        )
        write(f"content/{lang}/nach_unit/efl/_index.md", f"""---
title: "{index_title}"
description: "{index_lead}"
---

{index_lead}

<div class="card-grid">

{cards}
</div>
""")
        for k in range(5, 14):
            title = f"EFL — {klasse} {k}"
            lead = t("unit_efl_grade_lead", lang).format(k=k)
            fb = f'    unit_prefix: "efl_kl{k}"\n'
            write(f"content/{lang}/nach_unit/efl/kl{k:02d}.md",
                  stub(title, lead, fb))

        # ----- by unit (FLE): kl06..kl13 plus index ------
        index_title = t("unit_fle_overview", lang)
        index_lead = t("unit_fle_lead", lang)
        cards = "\n".join(
            f'<div class="entry-card">\n\n'
            f'### [{klasse} {k}](kl{k:02d}/)\n\n</div>\n'
            for k in range(6, 14)
        )
        write(f"content/{lang}/nach_unit/fle/_index.md", f"""---
title: "{index_title}"
description: "{index_lead}"
---

{index_lead}

<div class="card-grid">

{cards}
</div>
""")
        for k in range(6, 14):
            title = f"FLE — {klasse} {k}"
            lead = t("unit_fle_grade_lead", lang).format(k=k)
            fb = f'    unit_prefix: "fle_kl{k}"\n'
            write(f"content/{lang}/nach_unit/fle/kl{k:02d}.md",
                  stub(title, lead, fb))

        # ----- by unit (DaF): a1..c1 plus index ------
        index_title = t("unit_daf_overview", lang)
        index_lead = t("unit_daf_lead", lang)
        cards = "\n".join(
            f'<div class="entry-card">\n\n'
            f'### [{lvl.upper()}]({lvl}/)\n\n</div>\n'
            for lvl in levels
        )
        write(f"content/{lang}/nach_unit/daf/_index.md", f"""---
title: "{index_title}"
description: "{index_lead}"
---

{index_lead}

<div class="card-grid">

{cards}
</div>
""")
        for lvl in levels:
            title = f"DaF — {lvl.upper()}"
            lead = t("unit_daf_lvl_lead", lang).format(lvl=lvl.upper())
            fb = f'    unit_prefix: "daf_{lvl}"\n'
            write(f"content/{lang}/nach_unit/daf/{lvl}.md",
                  stub(title, lead, fb))


# -- main --------------------------------------------------------------

def main() -> None:
    emit_i18n()
    emit_legal()
    emit_landings()
    emit_overview()
    emit_root_picker()
    emit_view_stubs()
    print("scaffold complete.")


if __name__ == "__main__":
    main()
